# This file was generated by GoReleaser. DO NOT EDIT.
cask "climber-count" do
  desc "Telegram bot to report a people count in your local bouldering gym"
  homepage "https://github.com/eiri/climber-count"
  version "0.1.9"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "climber-count"

  on_macos do
    on_intel do
      url "https://github.com/eiri/climber-count/releases/download/v0.1.9/climber-count_Darwin_x86_64.tar.gz"
      sha256 "28e413d668c1784712889c662b2461b5838d1ed121530f19479b53fb93c089f5"
    end
    on_arm do
      url "https://github.com/eiri/climber-count/releases/download/v0.1.9/climber-count_Darwin_arm64.tar.gz"
      sha256 "27dd16583bd7f5fffef64e8b424e94799fe52d56a2403be99c0fd09217a5c346"
    end
  end

  on_linux do
    on_intel do
      url "https://github.com/eiri/climber-count/releases/download/v0.1.9/climber-count_Linux_x86_64.tar.gz"
      sha256 "eed0fcdaa6c1ddf63d8e4bd3f146b4c7129d72993564b7d2cdc739601b7d06f5"
    end
    on_arm do
      url "https://github.com/eiri/climber-count/releases/download/v0.1.9/climber-count_Linux_arm64.tar.gz"
      sha256 "01d0f64c419572d84ca90ebffae52b954b685b59892f30459502f0cf9e8e0a68"
    end
  end

  postflight do
    if system_command("/usr/bin/xattr", args: ["-h"]).exit_status == 0
      system_command "/usr/bin/xattr", args: ["-dr", "com.apple.quarantine", "#{staged_path}/taon"]
    end
  end

  # No zap stanza required
end
