# This file was generated by GoReleaser. DO NOT EDIT.
cask "taon" do
  name "taon"
  desc "Transform JSON into ASCII table"
  homepage "https://github.com/eiri/taon"
  version "0.3.8"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "taon"

  on_macos do
    on_intel do
      url "https://github.com/eiri/taon/releases/download/v#{version}/taon_Darwin_x86_64.tar.gz"
      sha256 "57a7b9eec1090ed0e4099be55e643ef4a709815e555567a96a0baedb58797d79"
    end
    on_arm do
      url "https://github.com/eiri/taon/releases/download/v#{version}/taon_Darwin_arm64.tar.gz"
      sha256 "ae957cf00eaec4403a3fe668e26604c9795abe254ae76936ef21920b0093696f"
    end
  end

  on_linux do
    on_intel do
      url "https://github.com/eiri/taon/releases/download/v#{version}/taon_Linux_x86_64.tar.gz"
      sha256 "583a6581bc6adf5e561b5da07a2ca98863f26b8bdced78df3cd0f215a008edd6"
    end
    on_arm do
      url "https://github.com/eiri/taon/releases/download/v#{version}/taon_Linux_arm64.tar.gz"
      sha256 "9521bf638a0332fdd8a55f2101ffe281408cdb1e9fb364c845a6b5f51537196d"
    end
  end

  postflight do
    if system_command("/usr/bin/xattr", args: ["-h"]).exit_status == 0
      system_command "/usr/bin/xattr", args: ["-dr", "com.apple.quarantine", "#{staged_path}/taon"]
    end
  end

  # No zap stanza required
end
