# This file was generated by GoReleaser. DO NOT EDIT.
cask "taon" do
  desc "Transform JSON into ASCII table"
  homepage "https://github.com/eiri/taon"
  version "0.3.7"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "taon"

  on_macos do
    on_intel do
      url "https://github.com/eiri/taon/releases/download/v0.3.7/taon_Darwin_x86_64.tar.gz"
      sha256 "834e97ed035d95e7d1c8c396d4da61163e6a864a7a07b52a527c2b6e49ce1127"
    end
    on_arm do
      url "https://github.com/eiri/taon/releases/download/v0.3.7/taon_Darwin_arm64.tar.gz"
      sha256 "938aec6c6d7742c17f3533ab65b9863af11678bb1f2cdfa3ba17a790bf2e71fd"
    end
  end

  on_linux do
    on_intel do
      url "https://github.com/eiri/taon/releases/download/v0.3.7/taon_Linux_x86_64.tar.gz"
      sha256 "429ee04016567b17008979e75b619477071b5290029e50fca4d519c841476629"
    end
    on_arm do
      url "https://github.com/eiri/taon/releases/download/v0.3.7/taon_Linux_arm64.tar.gz"
      sha256 "bcc20d568cedceb01f44042d43578c868a5710a9cb474f140a3da249cf87b113"
    end
  end

  postflight do
    if system_command("/usr/bin/xattr", args: ["-h"]).exit_status == 0
      system_command "/usr/bin/xattr", args: ["-dr", "com.apple.quarantine", "#{staged_path}/taon"]
    end
  end

  # No zap stanza required
end
