# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class ClimberCount < Formula
  desc "Telegram bot to report a people count in your local bouldering gym"
  homepage "https://github.com/eiri/climber-count"
  version "0.1.6"
  license "MIT"

  on_macos do
    on_intel do
      url "https://github.com/eiri/climber-count/releases/download/v0.1.6/climber-count_Darwin_x86_64.tar.gz"
      sha256 "2c1fecdade0d887adfc987f5379d323b987635a5a6529d4d56dc12901003e692"

      def install
        bin.install "climber-count"
      end
    end
    on_arm do
      url "https://github.com/eiri/climber-count/releases/download/v0.1.6/climber-count_Darwin_arm64.tar.gz"
      sha256 "b8d450c0417a6fce713c8e721f6cb7cbb1cb2dd3f656267a76262b0e7658f366"

      def install
        bin.install "climber-count"
      end
    end
  end

  on_linux do
    on_intel do
      if Hardware::CPU.is_64_bit?
        url "https://github.com/eiri/climber-count/releases/download/v0.1.6/climber-count_Linux_x86_64.tar.gz"
        sha256 "d19d06d76ecef34de546db7364e95a64b2932b28f284bea8a118591c9e4eee84"

        def install
          bin.install "climber-count"
        end
      end
    end
    on_arm do
      if Hardware::CPU.is_64_bit?
        url "https://github.com/eiri/climber-count/releases/download/v0.1.6/climber-count_Linux_arm64.tar.gz"
        sha256 "179ce106929d1f141bf25328953b07847293b178e1cb24babda495ef1bc8627c"

        def install
          bin.install "climber-count"
        end
      end
    end
  end
end
