# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class ClimberCount < Formula
  desc "Telegram bot to report a people count in your local bouldering gym"
  homepage "https://github.com/eiri/climber-count"
  version "0.1.7"
  license "MIT"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/eiri/climber-count/releases/download/v0.1.7/climber-count_Darwin_x86_64.tar.gz"
      sha256 "64d07629e3f66c4b26f00dfa14ff867005d988c238b8d98ac8e9462a0f850c36"

      def install
        bin.install "climber-count"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/eiri/climber-count/releases/download/v0.1.7/climber-count_Darwin_arm64.tar.gz"
      sha256 "df76b28e503c49e12eabbe58b976522db99e4da49f91c27595c95204579056aa"

      def install
        bin.install "climber-count"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel?
      if Hardware::CPU.is_64_bit?
        url "https://github.com/eiri/climber-count/releases/download/v0.1.7/climber-count_Linux_x86_64.tar.gz"
        sha256 "c23098ed41963960eb7d0161003b38888147f3c545f24511ac10d7c2edbdd965"

        def install
          bin.install "climber-count"
        end
      end
    end
    if Hardware::CPU.arm?
      if Hardware::CPU.is_64_bit?
        url "https://github.com/eiri/climber-count/releases/download/v0.1.7/climber-count_Linux_arm64.tar.gz"
        sha256 "d60c9f9d0ae5579a2d2c29c342297745c2e1e68974d85615baf972f9d53b80a3"

        def install
          bin.install "climber-count"
        end
      end
    end
  end
end
