# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class ClimberCount < Formula
  desc "Telegram bot to report a people count in your local bouldering gym"
  homepage "https://github.com/eiri/climber-count"
  version "0.1.5"
  license "MIT"

  on_macos do
    on_intel do
      url "https://github.com/eiri/climber-count/releases/download/v0.1.5/climber-count_Darwin_x86_64.tar.gz"
      sha256 "64b0a3b416f0cb84719617ef39cf00394b3d65027cb1a91282b4c1320103755a"

      def install
        bin.install "climber-count"
      end
    end
    on_arm do
      url "https://github.com/eiri/climber-count/releases/download/v0.1.5/climber-count_Darwin_arm64.tar.gz"
      sha256 "8a8c436b65eb3c15ec370caf73f40d27055d0b59035fbe41c15adf58e66aed78"

      def install
        bin.install "climber-count"
      end
    end
  end

  on_linux do
    on_intel do
      if Hardware::CPU.is_64_bit?
        url "https://github.com/eiri/climber-count/releases/download/v0.1.5/climber-count_Linux_x86_64.tar.gz"
        sha256 "59a217a8a42438ae395d1b57e0a3e16b529a9b565848ee3b4b980c8336ac11cb"

        def install
          bin.install "climber-count"
        end
      end
    end
    on_arm do
      if Hardware::CPU.is_64_bit?
        url "https://github.com/eiri/climber-count/releases/download/v0.1.5/climber-count_Linux_arm64.tar.gz"
        sha256 "4d0f2fc3a9934d65b111277cff31fce97483f1721915ad940fb624b028accd61"

        def install
          bin.install "climber-count"
        end
      end
    end
  end
end
