# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Taon < Formula
  desc "Transform JSON into ASCII table"
  homepage "https://github.com/eiri/taon"
  version "0.3.3"
  license "MIT"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/eiri/taon/releases/download/v0.3.3/taon_0.3.3_Darwin_x86_64.tar.gz"
      sha256 "a7e785df6ed4363f4ce0f4bfa10c2fb7206787012770659fd916e08b23c56846"

      def install
        bin.install "taon"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/eiri/taon/releases/download/v0.3.3/taon_0.3.3_Darwin_arm64.tar.gz"
      sha256 "48e118f933ec20c95e2db3cc659bf886a967a162b4b79c9c0d84b51e79f2541e"

      def install
        bin.install "taon"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel?
      url "https://github.com/eiri/taon/releases/download/v0.3.3/taon_0.3.3_Linux_x86_64.tar.gz"
      sha256 "88793dde752de0b226b224604eefd1051c4b6655b012b8075010ba33ad0bfe9f"

      def install
        bin.install "taon"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/eiri/taon/releases/download/v0.3.3/taon_0.3.3_Linux_arm64.tar.gz"
      sha256 "5dc18dade30431a414d9091e119e4a717901d016e3e3a4e76d46eb9a4e076fb7"

      def install
        bin.install "taon"
      end
    end
  end
end
