# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Taon < Formula
  desc "Transform JSON into ASCII table."
  homepage "https://github.com/eiri/taon"
  version "0.3.2"
  license "MIT"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/eiri/taon/releases/download/v0.3.2/taon_0.3.2_Darwin_x86_64.tar.gz"
      sha256 "8825afa0b8c3e1c4173ce9b25a5b1b17f150d13a21cfa4ffb451734760a0900c"

      def install
        bin.install "taon"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/eiri/taon/releases/download/v0.3.2/taon_0.3.2_Darwin_arm64.tar.gz"
      sha256 "e6068fa9045cd0c779b88dce1a1bb2fc3445b494036946fa4e31dd37f32b568c"

      def install
        bin.install "taon"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel?
      url "https://github.com/eiri/taon/releases/download/v0.3.2/taon_0.3.2_Linux_x86_64.tar.gz"
      sha256 "afc09c45cb038e24640d3c5bce125bb90bd2c3128cb4ae2ea229f77cf5843310"

      def install
        bin.install "taon"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/eiri/taon/releases/download/v0.3.2/taon_0.3.2_Linux_arm64.tar.gz"
      sha256 "8491918aafd475449e28fcbcd6829b7598bece6cbddfe9b44ccd96ed24fefc02"

      def install
        bin.install "taon"
      end
    end
  end
end
