name: Brew Test-Bot

on:
  pull_request:
    paths:
      - "Formula/**.rb"
  push:
    branches:
      - main
    paths:
      - "Formula/**.rb"

jobs:
  test:
    name: Run brew test-bot on ${{ matrix.os }}
    runs-on: ${{ matrix.os }}

    strategy:
      matrix:
        os: [ubuntu-latest, macos-latest]

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up Homebrew on Linux
        if: matrix.os == 'ubuntu-latest'
        uses: Homebrew/actions/setup-homebrew@master

      - name: Run test-bot
        run: |
          brew tap ${{ github.repository }}
          brew test-bot --tap=${{ github.repository }}
